PANEL_WIDTH = 200
PADDING = 12
BUTTON_HEIGHT = 36
BG_COLOR = (20, 20, 20, 220)
BUTTON_COLOR = (50, 50, 50)
BUTTON_HOVER = (70, 70, 70)
BUTTON_ACTIVE = (132, 87, 69)
TEXT_COLOR = (230, 230, 230)
TITLE_COLOR = (180, 220, 255)
TITLE_FONT = None
FONT = None

BUTTONS = []
PARSING_BUTTONS = {
    "ALGORITHM.SEEK_KINEMATIC"        : "SEEK KINEMATIC",
    "ALGORITHM.FLEE_KINEMATIC"        : "FLEE KINEMATIC",
    "ALGORITHM.ARRIVE_KINEMATIC"      : "ARRIVE KINEMATIC",
    "ALGORITHM.WANDER_KINEMATIC"      : "WANDER KINEMATIC",
    "ALGORITHM.SEEK_DYNAMIC"          : "SEEK DYNAMIC",
    "ALGORITHM.FLEE_DYNAMIC"          : "FLEE DYNAMIC",
    "ALGORITHM.ARRIVE_DYNAMIC"        : "ARRIVE DYNAMIC",
    "ALGORITHM.WANDER_DYNAMIC"        : "WANDER DYNAMIC",
    "ALGORITHM.ALIGN"                 : "ALIGN",
    "ALGORITHM.VELOCITY_MATCH"        : "VELOCITY MATCH",
    "ALGORITHM.PURSUE"                : "PURSUE",
    "ALGORITHM.EVADE"                 : "EVADE",
    "ALGORITHM.FACE"                  : "FACE",
    "ALGORITHM.LOOK_WHERE_YOURE_GOING": "LOOK W. Y. GOING",
    "ALGORITHM.PATH_FOLLOWING"        : "PATH FOLLOWING",
    "ALL"                             : "ALL",
    "NOTHING"                         : "NOTHING"
}
SELECTED_ALGORITHM = "NOTHING"