import enum

class ALGORITHM(str, enum.Enum):
    SEEK_KINEMATIC = "SEEK KINEMATIC"
    FLEE_KINEMATIC = "FLEE KINEMATIC"
    ARRIVE_KINEMATIC = "ARRIVE KINEMATIC"
    WANDER_KINEMATIC = "WANDER KINEMATIC"
    SEEK_DYNAMIC = "SEEK DYNAMIC"
    FLEE_DYNAMIC = "FLEE DYNAMIC"
    ARRIVE_DYNAMIC = "ARRIVE DYNAMIC"
    WANDER_DYNAMIC = "WANDER DYNAMIC"
    ALIGN = "ALIGN"
    VELOCITY_MATCH = "VELOCITY MATCH"
    PURSUE = "PURSUE"
    EVADE = "EVADE"
    FACE = "FACE"
    LOOK_WHERE_YOURE_GOING = "LOOK WHERE YOU'RE GOING"
    PATH_FOLLOWING = "PATH FOLLOWING"
    TEMP_PATH_FOLLOWING = "TEMP PATH FOLLOWING"