name: Build and Release Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build executable
        run: pyinstaller --onedir src/main.py --name DexelSurvivalDungeon

      - name: Prepare release folder
        run: |
          mkdir DexelSurvivalDungeon
          copy dist\DexelSurvivalDungeon\DexelSurvivalDungeon.exe DexelSurvivalDungeon\
          xcopy src\assets DexelSurvivalDungeon\assets\ /E /I

      - name: Create zip package
        run: powershell Compress-Archive -Path DexelSurvivalDungeon -DestinationPath DexelSurvivalDungeon-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DexelSurvivalDungeon-windows
          path: DexelSurvivalDungeon-windows.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onedir src/main.py --name DexelSurvivalDungeon
      
      - name: Package linux artifact
        run: |
          # empaqueta la carpeta dist/DexelSurvivalDungeon para subir como artifact
          tar -czf DexelSurvivalDungeon-linux.tar.gz -C dist DexelSurvivalDungeon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DexelSurvivalDungeon-linux
          path: DexelSurvivalDungeon-linux.tar.gz

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: DexelSurvivalDungeon-windows
          path: ./artifacts

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: DexelSurvivalDungeon-linux
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/DexelSurvivalDungeon-windows.zip
            artifacts/DexelSurvivalDungeon-linux.tar.gz

  update-web:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Actualizar enlaces y versión en la web
        run: |
          python3 update_web_links.py \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DexelSurvivalDungeon-windows.zip" \
            "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DexelSurvivalDungeon"

      - name: Commit y push de la web actualizada
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./index.html
          if ! git diff --quiet --cached -- ./index.html; then
            git commit -m "Actualiza enlaces de descarga y versión a ${{ github.ref_name }}"
            git push origin gh-pages
          else
            echo "No changes to ./index.html; skipping commit and push."
          fi